version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - db
